version: '3.8'

services:
  forensic_analyzer:
    build: .
    container_name: forensic_analyzer
    volumes:
      - ./samples:/samples
    restart: unless-stopped
    tty: true
    stdin_open: true
